FROM node:lts-alpine

# install simple http server for serving static content
RUN npm install -g http-server

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

RUN npm install

COPY . .

COPY ./.env.staging ./.env
# build app for production with minification
RUN npm run build
EXPOSE 8080

CMD [ "http-server", "dist" ]