# Generated by Django 3.2.4 on 2022-01-18 02:36

from django.db import migrations, models
import main.music_albums.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_albumcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='track_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.FileField(upload_to='music/tracks', validators=[main.music_albums.models.validate_file_extension]),
        ),
    ]
