# Generated by Django 3.2.4 on 2022-01-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220118_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='description',
            name='quote',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='description',
            name='text',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
