# Generated by Django 3.1.7 on 2021-05-05 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210407_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
