# Generated by Django 3.1.7 on 2021-05-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='credit',
            new_name='PostCredit',
        ),
        migrations.RenameModel(
            old_name='tag',
            new_name='PostTag',
        ),
    ]
