# Generated by Django 3.1.7 on 2021-05-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_picture_picturealbum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturealbum',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
