# Generated by Django 3.1.7 on 2021-05-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210506_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(upload_to='travels/pictures'),
        ),
    ]
