# Generated by Django 3.1.7 on 2021-05-08 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_musicalbum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.FileField(upload_to='music/tracks')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.musicalbum')),
            ],
        ),
    ]
