# Generated by Django 3.1.7 on 2021-05-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalbum',
            name='artist',
            field=models.CharField(max_length=20),
        ),
    ]
