# Generated by Django 3.2.4 on 2021-06-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_song_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, max_length=800)),
                ('picture', models.ImageField(upload_to='descriptions/')),
                ('quote', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='main.musicalbum'),
        ),
    ]
